# fly.toml app configuration file generated for communique-staging on 2023-06-27T20:17:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "communique-staging"
primary_region = "sjc"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
