name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    environment: Development
    env:
      TINYMCE_KEY: ${{ secrets.TINYMCE_KEY }}
      DATABASE_URL: ${{ secrets.database_url }}
      FINGERPRINTJS_KEY: ${{ secrets.FINGERPRINTJS_KEY }}
      FINGERPRINTJS_SERVER_KEY: ${{  secrets.FINGERPRINTJS_SERVER_KEY }}
      FINGERPRINTJS_URL: ${{ secrets.FINGERPRINTJS_URL }}
      FINGERPRINTJS_APIURL: ${{ secrets.FINGERPRINTJS_APIURL }}
      FINGERPRINTJS_SCRIPTURL: ${{ secrets.FINGERPRINTJS_SCRIPTURL }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Generate dotenv file
        run: |
          cat <<EOF > .env
          TINYMCE_KEY="$TINYMCE_KEY"
          DATABASE_URL="$DATABASE_URL"
          FINGERPRINTJS_KEY="$FINGERPRINTJS_KEY"
          FINGERPRINTJS_SERVER_KEY="$FINGERPRINTJS_SERVER_KEY"
          FINGERPRINTJS_URL="$FINGERPRINTJS_URL"
          EOF
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
