name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    environment: Development
    env:
      TINYMCEKEY: ${{ secrets.tinymcekey }}
      DATABASE_URL: ${{ secrets.database_url }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Generate dotenv file
        run: |
          cat <<EOF >  ${GITHUB_WORKSPACE}/.env
          TINYMCEKEY="$TINYMCEKEY"
          DATABASE_URL="$DATABASE_URL"
          EOF
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
